### ISSUE TITLE
Preview of document using control in Custom Page

### ISSUE THREAD

**Issue by frogozinski** [AHeizenberg/AttachmentControlPCF#1]
When using custom page in model driven app with this control ( in editor it works pefect ) the following error occurs
when trying to Preview attached document:

Error Details: Error: Invalid PDF url data: either string or URL-object is expected in the url property.
    at getUrlProp (webpack://pcf_tools_652ac3f36e1e4bca82eb3c1dc44e6fad/./node_modules/react-pdf/node_modules/pdfjs-dist/build/pdf.js?:22:28264)
    at Object.getDocument (webpack://pcf_tools_652ac3f36e1e4bca82eb3c1dc44e6fad/./node_modules/react-pdf/node_modules/pdfjs-dist/build/pdf.js?:22:22590)
    at loadDocument (webpack://pcf_tools_652ac3f36e1e4bca82eb3c1dc44e6fad/./node_modules/react-pdf/dist/esm/Document.js?:344:73)
    at Bh (https://content.powerapps.com/resource/app/hg86122f107g8/publish/js/pa.oss.bundle2.js:326:456)
    at Dj (https://content.powerapps.com/resource/app/hg86122f107g8/publish/js/pa.oss.bundle2.js:362:476)
    at unstable_runWithPriority (https://content.powerapps.com/resource/app/hg86122f107g8/publish/js/pa.oss.bundle2.js:192:260)
    at Da (https://content.powerapps.com/resource/app/hg86122f107g8/publish/js/pa.oss.bundle2.js:260:280)
    at xb (https://content.powerapps.com/resource/app/hg86122f107g8/publish/js/pa.oss.bundle2.js:362:231)
    at https://content.powerapps.com/resource/app/hg86122f107g8/publish/js/pa.oss.bundle2.js:362:138
    at U (https://content.powerapps.com/resource/app/hg86122f107g8/publish/js/pa.oss.bundle2.js:183:398)

Activity Id: dae83e22-2a41-4668-89b4-451ed72a3e7d

**Comment by AHeizenberg** [comment]
Thanks for sharing this I will take a look into it

**Comment by frogozinski** [comment]
Hi, any chance to get a version without previous files? I would love to use it but i cant roll out with error

**Comment by frogozinski** [comment]
Or can you provide the source code of control to try to fix the error.
